# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserLogin', '0005_auto_20160618_2347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_title', models.CharField(max_length=50)),
                ('request_desc', models.CharField(max_length=1500)),
                ('request_responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserLogin.UserLogin')),
            ],
        ),
    ]
