# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 04:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='request_responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
