# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-04 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRequest', '0002_auto_20160619_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_title', models.CharField(max_length=50, null=True)),
                ('request_desc', models.CharField(max_length=1500)),
                ('request_user', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='request_responder',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='request_user',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
