# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserRequest', '0003_auto_20160704_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_dentist',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
