# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0003_auto_20160713_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateField(default=datetime.date(2016, 7, 14)),
        ),
    ]
