# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tips', '0004_auto_20160714_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='date',
            field=models.DateField(default=datetime.date(2016, 7, 15)),
        ),
        migrations.AlterField(
            model_name='tip',
            name='image',
            field=models.ImageField(null=True, upload_to='tips_image/'),
        ),
    ]
