# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('profile_pic', models.ImageField(upload_to='profile_image')),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=5)),
                ('enable', models.BooleanField(default=True)),
                ('accessToken', models.CharField(max_length=1000)),
                ('login_type', models.CharField(max_length=20)),
            ],
        ),
    ]
