# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='accessToken',
            new_name='access_token',
        ),
    ]
