# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0003_auto_20160618_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='profile_pic',
            field=models.ImageField(blank=True, default=True, upload_to='profile_image'),
        ),
    ]
