# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0005_auto_20160618_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='gender',
            field=models.CharField(max_length=5),
        ),
    ]
