# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0006_auto_20160703_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='profile_pic',
        ),
    ]
