# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0012_auto_20160703_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
