# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserLogin', '0013_auto_20160703_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='user_dentist',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
